### ISSUE TITLE
Suggest 

### ISSUE THREAD

**Issue by SillierShark195** [Joestarfish/FarmChest#1]
Make support economy api and sell in sell.yml
When player sneak and tap chest show UI sell yes or no

**Comment by Joestarfish** [comment]
Hi and thanks for your idea.

This goes somewhat beyond the scope of this plugin and I felt like it would benefit from being usable more freely, so i made it into another plugin.

You can download it from [poggit](https://poggit.pmmp.io/ci/Joestarfish/SellWand/SellWand) or look at the repo: https://github.com/Joestarfish/SellWand

**Comment by SillierShark195** [comment]
Done
